const animalsWordRounds = [
  { word: "gato", category: "animales" },
  { word: "perro", category: "animales" },
  { word: "pez", category: "animales" },
  { word: "pájaro", category: "animales" },
  { word: "vaca", category: "animales" },
  { word: "caballo", category: "animales" },
  { word: "cerdo", category: "animales" },
  { word: "oveja", category: "animales" },
  { word: "pollo", category: "animales" },
  { word: "pato", category: "animales" },
  { word: "tigre", category: "animales" },
  { word: "león", category: "animales" },
  { word: "elefante", category: "animales" },
  { word: "jirafa", category: "animales" },
  { word: "mono", category: "animales" },
  { word: "oso", category: "animales" },
  { word: "zorro", category: "animales" },
  { word: "conejo", category: "animales" },
  { word: "ardilla", category: "animales" },
  { word: "murciélago", category: "animales" },
  { word: "iguana", category: "animales" },
  { word: "cocodrilo", category: "animales" },
  { word: "hipopótamo", category: "animales" },
  { word: "rinoceronte", category: "animales" },
  { word: "camello", category: "animales" },
  { word: "avestruz", category: "animales" },
  { word: "pingüino", category: "animales" },
  { word: "ballena", category: "animales" },
  { word: "delfín", category: "animales" },
];

const natureWordRounds = [
  { word: "árbol", category: "naturaleza" },
  { word: "flor", category: "naturaleza" },
  { word: "pasto", category: "naturaleza" },
  { word: "sol", category: "naturaleza" },
  { word: "luna", category: "naturaleza" },
  { word: "nube", category: "naturaleza" },
  { word: "lluvia", category: "naturaleza" },
  { word: "nieve", category: "naturaleza" },
  { word: "viento", category: "naturaleza" },
  { word: "arco iris", category: "naturaleza" },
  { word: "montaña", category: "naturaleza" },
  { word: "río", category: "naturaleza" },
  { word: "mar", category: "naturaleza" },
  { word: "playa", category: "naturaleza" },
  { word: "desierto", category: "naturaleza" },
  { word: "volcán", category: "naturaleza" },
  { word: "iceberg", category: "naturaleza" },
  { word: "cascada", category: "naturaleza" },
  { word: "bosque", category: "naturaleza" },
  { word: "pradera", category: "naturaleza" },
  { word: "isla", category: "naturaleza" },
  { word: "caverna", category: "naturaleza" },
  { word: "acantilado", category: "naturaleza" },
  { word: "valle", category: "naturaleza" },
  { word: "jungla", category: "naturaleza" },
  { word: "bahía", category: "naturaleza" },
  { word: "lago", category: "naturaleza" },
  { word: "huracán", category: "naturaleza" },
];

const vehiclesWordRounds = [
  { word: "coche", category: "vehículos" },
  { word: "bicicleta", category: "vehículos" },
  { word: "tren", category: "vehículos" },
  { word: "avión", category: "vehículos" },
  { word: "barco", category: "vehículos" },
  { word: "autobús", category: "vehículos" },
  { word: "camión", category: "vehículos" },
  { word: "motocicleta", category: "vehículos" },
  { word: "helicóptero", category: "vehículos" },
  { word: "cohete", category: "vehículos" },
  { word: "triciclo", category: "vehículos" },
  { word: "patineta", category: "vehículos" },
  { word: "carroza", category: "vehículos" },
  { word: "caravana", category: "vehículos" },
  { word: "carretilla", category: "vehículos" },
  { word: "carro", category: "vehículos" },
  { word: "grúa", category: "vehículos" },
  { word: "ambulancia", category: "vehículos" },
  { word: "taxi", category: "vehículos" },
  { word: "remolque", category: "vehículos" },
  { word: "barredora", category: "vehículos" },
  { word: "bulldozer", category: "vehículos" },
  { word: "excavadora", category: "vehículos" },
  { word: "montacargas", category: "vehículos" },
  { word: "tractor", category: "vehículos" },
  { word: "grúa torre", category: "vehículos" },
  { word: "coche de bomberos", category: "vehículos" },
  { word: "coche de policía", category: "vehículos" },
];

const homeWordRounds = [
  { word: "cama", category: "hogar" },
  { word: "silla", category: "hogar" },
  { word: "mesa", category: "hogar" },
  { word: "lámpara", category: "hogar" },
  { word: "sofá", category: "hogar" },
  { word: "nevera", category: "hogar" },
  { word: "inodoro", category: "hogar" },
  { word: "lavabo", category: "hogar" },
  { word: "bañera", category: "hogar" },
  { word: "televisión", category: "hogar" },
  { word: "cocina", category: "hogar" },
  { word: "horno", category: "hogar" },
  { word: "microondas", category: "hogar" },
  { word: "lavadora", category: "hogar" },
  { word: "plancha", category: "hogar" },
  { word: "aspiradora", category: "hogar" },
  { word: "ventilador", category: "hogar" },
  { word: "calefactor", category: "hogar" },
  { word: "alfombra", category: "hogar" },
  { word: "cortina", category: "hogar" },
  { word: "cojín", category: "hogar" },
  { word: "toalla", category: "hogar" },
  { word: "sábana", category: "hogar" },
  { word: "manta", category: "hogar" },
  { word: "almohada", category: "hogar" },
  { word: "cuadro", category: "hogar" },
];

const clothesWordRounds = [
  { word: "camisa", category: "ropa" },
  { word: "pantalones", category: "ropa" },
  { word: "calcetines", category: "ropa" },
  { word: "zapatos", category: "ropa" },
  { word: "sombrero", category: "ropa" },
  { word: "gafas", category: "ropa" },
  { word: "bufanda", category: "ropa" },
  { word: "guantes", category: "ropa" },
  { word: "chaqueta", category: "ropa" },
  { word: "falda", category: "ropa" },
  { word: "corbata", category: "ropa" },
  { word: "vestido", category: "ropa" },
  { word: "botas", category: "ropa" },
  { word: "pantuflas", category: "ropa" },
  { word: "bañador", category: "ropa" },
  { word: "bikini", category: "ropa" },
  { word: "gorra", category: "ropa" },
  { word: "cinturón", category: "ropa" },
  { word: "joyas", category: "ropa" },
  { word: "reloj", category: "ropa" },
  { word: "paraguas", category: "ropa" },
];

const foodWordRounds = [
  { word: "manzana", category: "comida" },
  { word: "plátano", category: "comida" },
  { word: "fresa", category: "comida" },
  { word: "piña", category: "comida" },
  { word: "limón", category: "comida" },
  { word: "pan", category: "comida" },
  { word: "queso", category: "comida" },
  { word: "arroz", category: "comida" },
  { word: "huevo", category: "comida" },
  { word: "café", category: "comida" },
  { word: "leche", category: "comida" },
  { word: "carne", category: "comida" },
  { word: "pescado", category: "comida" },
  { word: "pollo", category: "comida" },
  { word: "verduras", category: "comida" },
  { word: "frutas", category: "comida" },
  { word: "ensalada", category: "comida" },
  { word: "sopa", category: "comida" },
  { word: "pasta", category: "comida" },
  { word: "pizza", category: "comida" },
  { word: "hamburguesa", category: "comida" },
  { word: "hot dog", category: "comida" },
  { word: "sushi", category: "comida" },
];
const WordRounds = [
  ...animalsWordRounds,
  ...natureWordRounds,
  ...vehiclesWordRounds,
  ...homeWordRounds,
  ...clothesWordRounds,
  ...foodWordRounds,
];

export default WordRounds;
